### ISSUE TITLE
Backport?

### ISSUE THREAD

**Issue by cpm9** [jumpcutfindo/happy-holidays#10]
Just wondering if it would be possible to backport 1.2 from 1.17.1 to 1.16.5? Not trying to be rude, I know that might be lots of work. Thanks!

**Comment by jumpcutfindo** [comment]
I think it might be possible, but considering how much of the content of 1.17+ I've already incorporated into the mod as of Happy Holidays 1.2, I think I'd only do so if there was a huge demand for a backport. Sorry!
