### ISSUE TITLE
1.18.1 Crash on initialization

### ISSUE THREAD

**Issue by dragoneyeeon** [jumpcutfindo/happy-holidays#16]
[crash-2021-12-13_20.38.00-fml.txt](https://github.com/jumpcutfindo/happy-holidays/files/7708027/crash-2021-12-13_20.38.00-fml.txt)

**Comment by jumpcutfindo** [comment]
Seems like you haven't included GeckoLib alongside your installation, you can download it (here)[https://www.curseforge.com/minecraft/mc-mods/geckolib]!
